server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      host: 0.0.0.0
      port: 6379
      password: 123123
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  ai:
    openai:
      api-key: sk-d32d5e0031684ef7b32eb356941b4e2c
      base-url: https://api.deepseek.com
      chat:
          options:
            # 指定支持工具调用的模型
            model: deepseek-chat
            # 温度调低，保证函数调用的准确性
            temperature: 0.1
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug